spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cart_service
    username: root
    password: jiwon1923
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8dialect